# Generated by Django 3.0.5 on 2020-04-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='amount_parking_spots',
            field=models.IntegerField(default=0, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='Longitude'),
        ),
    ]
