# Generated by Django 3.0.5 on 2020-05-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_auto_20200426_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='amount_parking_spots',
            field=models.IntegerField(default=0, verbose_name='Total de Vagas'),
        ),
    ]
