# Generated by Django 3.0.5 on 2020-04-03 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0001_initial'),
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(auto_now_add=True, verbose_name='Check In')),
                ('check_out', models.DateTimeField(auto_now=True, verbose_name='Check Out')),
                ('total_time', models.TimeField(blank=True, null=True, verbose_name='Tempo Total')),
                ('total_price', models.FloatField(default=0, verbose_name='Preço Total')),
                ('its_coming_out', models.BooleanField(default=False, verbose_name='Está Saindo?')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.Driver', verbose_name='Motorista')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.Parking', verbose_name='Estacionamento')),
                ('parking_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.ParkingSpot', verbose_name='Vaga')),
            ],
            options={
                'verbose_name': 'Livro de Registro',
                'verbose_name_plural': 'Livro de Registros',
            },
        ),
    ]
