# Generated by Django 3.0.5 on 2020-04-03 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=20, unique=True, verbose_name='CNPJ')),
                ('parking_name', models.CharField(max_length=150, verbose_name='Nome do Estacionamento')),
                ('country', models.CharField(max_length=50, verbose_name='País')),
                ('state', models.CharField(max_length=50, verbose_name='Estado')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('place', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('place_number', models.PositiveIntegerField(verbose_name='Número do Logradouro')),
                ('complement', models.CharField(blank=True, max_length=200, null=True, verbose_name='Logradouro')),
                ('latitude', models.BigIntegerField(default=0, verbose_name='Latitude')),
                ('longitude', models.BigIntegerField(default=0, verbose_name='Longitude')),
                ('opening_time', models.DateTimeField(verbose_name='Horairo de Abertura')),
                ('closing_time', models.DateTimeField(verbose_name='Horairo de Abertura')),
                ('price_per_hour', models.FloatField(verbose_name='Preço por Hora')),
                ('created_date_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_date_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Estacionamento',
                'verbose_name_plural': 'Estacionamentos',
            },
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.Driver', verbose_name='Motorista')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.Parking', verbose_name='Estacionamento')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
            },
        ),
    ]
