# Generated by Django 3.0.5 on 2020-04-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='closing_time',
            field=models.DateTimeField(verbose_name='Horairo de Fechamento'),
        ),
    ]
