# Generated by Django 3.0.5 on 2020-04-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_auto_20200403_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='closing_time',
            field=models.TimeField(verbose_name='Horairo de Fechamento'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='complement',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='opening_time',
            field=models.TimeField(verbose_name='Horairo de Abertura'),
        ),
    ]
