# Generated by Django 3.0.5 on 2020-04-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': '- Status',
                'verbose_name_plural': '- Status',
            },
        ),
    ]
