# Generated by Django 3.0.5 on 2020-05-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='book_to',
            field=models.TimeField(blank=True, null=True, verbose_name='Reserva para às'),
        ),
    ]
