# Generated by Django 3.0.5 on 2020-06-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20200602_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='book_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reserva para às'),
        ),
    ]
